name: Pydantic PR Checks
author: Amir Kadivar <amir@amirkdv.ca>
description: Checks PR guidelines and comments on errors

inputs:
  repo:
    description: The Github repository in 'user/project' format
    required: true
  number:
    description: The PR number in the given repository
    required: true
  token:
    description: Github access token to view and comment on a PR
    required: true

runs:
  using: docker
  image: Dockerfile

branding:
  icon: check-square
  color: blue
