name: CI

on:
- push
- pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up python
        run: |
          pip install -r requirements.txt

      - name: test
        run: |
          make test

      - name: lint
        run: |
          make lint
